#!/bin/bash

if [[ "x$CROSS_GCC" == "x1" ]] ; then
    echo "i686-pc-toaru-gcc"
    exit 0
fi

if [[ -n `which clang` ]] ; then
	echo "clang -ccc-host-triple i686-elf"
elif [[ -n `which i686-pc-toaru-gcc` ]] ; then
	echo "i686-pc-toaru-gcc"
else
	echo "Error: No usable compiler found." >&2
	exit 1
fi
