#!/bin/bash
. util/cpad.sh

CMD=`cpad "$1" 8 " "`
if [[ -s /tmp/.build-errors ]] ; then
    cat /tmp/.build-errors
    echo -e -n "\r\033[1;33m${CMD}${2}\033[0m\n"
else
    echo -e -n "\r\033[A\033[1;32m${CMD}${2}\033[0m\033[K\n"
fi
