#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/cpad.sh"

CMD=`cpad "$1" 8 " "`
if [[ -s /tmp/.`whoami`-build-errors ]] ; then
    echo -e -n "\r\033[1;33m${CMD}${2}\033[0m\n"
    cat /tmp/.`whoami`-build-errors
else
    echo -e -n "\r\033[1;32m${CMD}${2}\033[0m\033[K\n"
fi
