.TH PONG 6 "April, 2026"

.SH NAME
\fBpong\fP \- table tennis game with multiple windows

.SH DESCRIPTION
Play a simple table tennis game by dragging the racket window on the left.
.PP
Pressing \fBq\fP will exit the application.

.SH NOTES
This application was intended as an early demonstration of the windowing environment
and how applications are informed of, and can respond to, changes to the locations
of their windows.
.PP
The application will play sounds using the
.IR beep (1)
utility.

.SH SEE ALSO
.BR compositor (1)
