.TH ABOUT 1 "April, 2026"

.SH NAME
\fBabout\fP \- display a window with application information

.SH SYNOPSIS
\fBabout\fP
.br
\fBabout\fP \fItitle\fP \fIicon\fP \fIversion\fP \fIdescription\fP [\fIx\fP \fIy\fP]

.SH DESCRIPTION
The \fBabout\fP utility displays a window describing an application.
.PP
This utility is a wrapper around
.IR about\-dialog (1),
mapping the arguments of the \fBabout\fP from prior releases of ToaruOS
to the format accepted by the new utility.
.PP
With no arguments, the utility will describe the operating system.
.SS Arguments
When arguments are provided, they are translated as follows:

.TP
.I title
Becomes the argument to the \fB\-\-title\fP option.

.TP
.I icon
Becomes the argument to the \fB\-\-logo\fP option.
(Not to be confused with the \fB\-\-icon\fP option, which will be set to \fB"star"\fP.)

.TP
.I version
Becomes the argument to the \fB\-\-name\fP option.

.TP
.I description
Split on new lines, each provided as regular argument to
.IR about\-dialog (1).

.TP
\fIx\fP, \fIy\fP
\fB"\fIx\fB,\fIy\fB"\fR becomes the the argument to the \fB\-\-at\fP option.

.SH SEE ALSO
.BR about\-dialog (1),
.BR sysinfo (1),
.BR uname (1)
