.TH CALCULATOR 1 "March, 2026"

.SH NAME
\fBCalculator\fP \- Simple GUI calculator for ToaruOS.

.SH DESCRIPTION
This is a simple calculator GUI that is, in reality, a \fBKuroko\fP REPL.
The buttons in the GUI display normal mathematical symbols but insert their
programmatic equivalents into the text box. Code can also be manually typed
with the keyboard.
.PP
The calculator will display the results of each REPL expression in a nice
big font.
.PP
Because Kuroko has native support for bigints, integer math generally works
well, but fractional math will suffer from the usual floating point issues.

.SH SEE ALSO
.BR kuroko (1)

