.TH CPUWIDGET 1 "March, 2026"

.SH NAME
\fBcpuwidget\fP \- Graphically display CPU, memory, and network usage.

.SH DESCRIPTION
This is a graphical \fBSystem Monitor\fP utility that displays cute graphs
of CPU usage, memory usage, and network traffic.
.PP
The graphs update continuously, use smoothed curves, and animate.

.SH HISTORY
The visual design of this utility is based on the GNOME System Monitor.

.SH SEE ALSO
.BR top (1)
