.TH FETCH 1 "April, 2026"

.SH NAME
\fBfetch\fP \- download files

.SH SYNOPSIS
\fBfetch\fP [\fB\-hOvmp\fP] [\fB\-c\fP \fIcookies\fP] [\fB\-o\fP \fIfile\fP] [\fB\-u\fP \fIfile\fP]
[\fB\-s\fP \fIspeed\fP] \fIURL\fP

.SH DESCRIPTION
The \fBfetch\fP utility downloads files over HTTP.
.PP
Supported options include:

.TP
.B \-h
Show headers set by the server.

.TP
.B \-O
Save the file to a filename based on the last element of the path in the URL.

.TP
.B \-v
Show progress of the download. If the server provided a content size, a progress
bar will also be displayed.

.TP
.B \-m
Print machine readable output. In addition to any progress display from \-v,
this option will output a line containing the current download size, a space,
and then the total download size (which may be unset), and finally print the
string "done" when the download has completed, to standard output. This can
be read to display a graphical progress bar.

.TP
.B \-p
Prompt for a password to be placed in the body of an upload as a form data
field called "password". You probably don't want this.
This does \fInot\fP set an authentication header.

.TP
.B \-c \fIcookies\fP
Set the \fIcookies\fP to be sent with the request.

.TP
.B \-o \fIfile\fP
Write the output to a given \fIfile\fP instead of standard output.

.TP
.B \-u \fIfile\fP
Upload the contents of \fIfile\fP as a form value named "file".
You probably don't want this.

.TP
.B \-s \fIspeed\fP
Sleeps for \fIspeed\fP ms between sending blocks of 1024 bytes when uploading
a file with the \fB\-u\fP option.

.SH NOTES
This utility does not support TLS connections. An alternative version of this
utility, called \fBfetch\-tls\fP, may be available from the package repository,
which does support TLS. Options supported by that utility may differ from this
one.
.PP
This utility will always return 0 when a download has completed "successfully",
regardless of the response code from the server. That is to say, if the server
sends a 404 response and the utility downloads it, it will still exit with 0.

.SH SEE ALSO
.BR fetch\-tls (1)
