.TH HELLO 1

.SH NAME
\fBhello\fP \- Print "Hello, world."

.SH DESCRIPTION
This utility only really exists because the GNU project has one, so we
should have one, too.
.PP
Like the GNU one, this \fBhello\fP is somewhat of a template for how
to format C sources in ToaruOS, at least as far as the copyright
comment at the top of the file goes.
