.TH KILL 1 "March, 2026"

.SH NAME
\fBkill\fP \- send signals to processes

.SH SYNOPSIS
\fBkill\fP [\-\fIsignal\fP] \fIpid\fP...
.br
\fBkill\fP [\fB\-s\fP \fIsignal\fP] \fIpid\fP...
.br
\fBkill\fP \fB\-l\fP [\fIexit_status\fP]

.SH DESCRIPTION
Sends \fBSIGKILL\fP, or the specified \fIsignal\fP, to each specified \fIpid\fP.
Signals can be specified either with the \fB\-s\fP flag, or by just prefixing them
with a \-.

.TP
.B \-s \fIsignal\fP
Specify the signal to send.

.TP
.B \-l [\fIexit_status\fP]
With no argument, prints all of the possible signal names.
.sp
With \fIexit_status\fP, interprets that status and prints the signal that
may have produced it. \fIexit_status\fP can also just be an integer signal
value.

.SH EXIT STATUS
.TP
0
All \fIpid\fPs were signalled, or a match for an \fIexit_status\fP was found,
or signals were listed successuflly.

.TP
1
At least one \fIpid\fP failed to be signalled, or no match for an \fIexit_status\fP
was found, or some other error occurred.

.SH BUGS
This implementation sends \fBSIGKILL\fP but it should probably send \fBSIGTERM\fP.

.SH SEE ALSO
.BR kill (2),
.BR killall (3)
