.TH KRK_YUTANI_TEST 1 "April, 2026"

.SH NAME
\fBkrk_yutani_test.krk\fP \- windowed demo application

.SH DESCRIPTION
This script is a demonstration of how to use the Kuroko Yutani bindings to produce a windowed application.
.PP
The script demonstrates drawing a window with decorations and a menu bar, customizing the menubar
with new widgets, painting to the main part of the window, and queueing asynchronous events.

.SH SEE ALSO
.BR kuroko (1),
.BR compositor (1),
.BR _yutani2 (3krk),
.BR yutani_mainloop (3krk)
