.TH MKDIR 1 "April, 2026"

.SH NAME
\fBmkdir\fP \- create directories

.SH SYNOPSIS
\fBmkdir\fP [\fB\-p\fP] \fIdir\fP...

.SH DESCRIPTION
The \fBmkdir\fP utility creates directories.

.TP
.B \-p
Recursively create parent directories. When this option is specified,
it is not an error if a directory already exists.

.SH SEE ALSO
.BR mkdir (2)
