.TH NETTY 1 "April, 2026"

.SH NAME
\fBnetty\fP \- host terminal sessions over remote sockets

.SH SYNOPSIS
\fBnetty\fP [\fB\-a\fP \fIuser\fP] \fIremote\fP:\fIport\fP [\fITERM\fP]

.SH DESCRIPTION
\fBnetty\fP connects to a \fIremote\fP TCP socket and then serves a terminal session with
.IR login\-loop (1),
providing a "reverse shell".
.PP
If a \fITERM\fP argument is provided, the environment variable will be set.

.SS Options
.TP
.B -a \fIuser\fP
Instead of
.IR login\-loop (2),
runs
.IR login (2)
with \fB\-f \f(BIuser\fR, which will automatically authenticate as that user.

.SH EXAMPLE
The remote terminal can be configured with something like:

    stty raw -echo; nc -l 127.0.0.1 8090; stty sane

And then \fBnetty\fP can be run with:

    sudo netty 10.0.2.2:8090 xterm-256color

.SH SECRUITY
The terminal session is served over clear text and should not be used for
an actual remote system over a network. The intent of this utility is to provide
a faster shell interface from a host operating system to a virtual machine, as
serial consoles, even in QEMU, can be very slow.
.PP
Only root is allowed to operate \fBnetty\fP, in part because it runs \fIlogin\-loop\fP,
which will require root anyway.

.SH SEE ALSO
.BR login\-loop (1),
.BR getty (1)
