.TH PACKAGE-MANAGER 1 "April, 2026"

.SH NAME
\fBpackage\-manager\fP \- graphical interface to msk

.SH DESCRIPTION
The \fBPackage Manager\fP application provides a graphical interface to
.IR msk (1).
.PP
Packages are presented in a list.
The installation status of each package is indicated by whether its icon is transparent
(uninstalled) or opaque (installed).
Double clicking a package will prompt to install it.

.SH NOTES
The application must be run as root.

.SH SEE ALSO
.BR msk (1)
