.TH PATH_DEMO.KRK 1 "April, 2026"

.SH NAME
\fBpath_demo.krk\fP \- demonstration of the \fBlibtoaru_text\fP Kuroko bindings

.SH DESCRIPTION
This script demonstrates how to use the Kuroko bindings to the \fBlibtoaru_text\fP library.
.PP
The \fBlibtoaru_text\fP is more than just a TrueType text renderer.
The path rasterizeration routines it uses to draw text are available to users to
draw other arbitrary shapes.

.SH SEE_ALSO
.BR libtoaru_text (3),
.BR kuroko (1),
.BR _yutani2 (3krk)
