.TH PIANO 1 "March, 2026"

.SH NAME
\fBpiano\fP \- Play notes with the keyobard.

.SH DESCRIPTION
This utility plays notes on the PC speaker in response to keyboard presses.
.PP
This utility only works with the PC speaker and is unlikely to be ported to a PCM backend.
.PP
If you want to play tones and can not use the PC speaker, try
.IR beep (1)
instead.

.SH SEE ALSO
.BR beep (1)
