.TH PING 1 "March, 2026"

.SH NAME
\fBping\fP \- issue ICMP echo requests

.SH SYNOPSIS
\fBping\fP [\fB\-4\fP|\fB\-6\fP] \fIhost\fP

.SH DESCRIPTION
Issue a series of ICMP echo requests to a remote host, waiting for and summarizing replies.

.SS Options

.TP
.B \-4
Use IPv4 only.
This option actually does nothing but is provided for compatibility.

.TP
.B \-6
Use IPv6 only.
This option will always produce an error, as IPv6 support is not available.

.TP
.B \-c \fIcount\fP
Send (and wait for) \fIcount\fP pings before exiting.
The default is to send pings indefinitely.

.SH SEE ALSO
.BR ifconfig (1)
