.TH PLAY 1 "March, 2026"

.SH NAME
\fBplay\fP \- play back raw PCM

.SH SYNOPSIS
\fBplay\fP [\fB\-d\fP \fIdsp_path\fP] \fIfile\fP

.SH DESCRIPTION
Play back a file containing raw, signed, 16-bit little-endian, stereo PCM samples at 48KHz.
This is really just a glorified \fBcat\fP, but maybe one day it'll suport RIFF files...

.TP
.B \-d \fIdsp_path\fP
Specify the location of the audio device file.

.SH SEE ALSO
.BR beep (1)
