.TH READLINK 1 "April, 2026"

.SH NAME
\fBreadlink\fP \- display the target of a symbolic link

.SH SYNOPSIS
\fBreadlink\fP \fIpath\fP

.SH DESCRIPTION
The \fBreadlink\fP utility shall print the target of a symbolic link
to standard output.

.SS Options
None.

.SH EXIT STATUS
.TP
0
The link was successfully read.
.TP
1
An error occurred.

.SH AUTHOR
This implementation was written by Mike Gerow.
.PP
This manual page was written by K. Lange.

.SH SEE ALSO
.BR readlink (2)
