.TH REALPATH 1 "April, 2026"

.SH NAME
\fBrealpath\fP \- print absolute path

.SH SYNOPSIS
\fBrealpath\fP [\fB\-e\fP|\fB\-E\fP] \fIpath\fP...

.SH DESCRIPTION
The \fBrealpath\fP utility prints the canonicalized absolute path for each argument.

.SS Options
.TP
.B \-e
If any element of \fIpath\fP does not resolve, canonicalization fails.

.TP
.B \-E
If the final element of \fIpath\fP does not resolve, this is not treated as an error.


.SH SEE ALSO
.BR realpath (3)

