.TH SET-WALLPAPER 1 "April, 2026"

.SH NAME
\fBset\-wallpaper.sh\fP \- update user's wallpaper

.SH SYNOPSIS
\fBset\-wallpaper.sh\fP \fIfile\fP

.SH DESCRIPTION
This shell script is a helper to set the user's wallpaper and inform the instance of
.IR file\-browser (1)
managing the desktop that it should reload it.

.SH SEE ALSO
.BR wallpaper\-picker (1),
.BR file\-browser (1)
