.TH TOP 1 "March, 2026"
.SH NAME
top \- Interactively display running processes.
.SH SYNOPSIS
\fBtop\fP [\fB\-d\fP \fIdelay\fP] [\fB\-l\fP \fIsamples\fP] [\fB\-H\fP]
.SH DESCRIPTION
This \fBtop\fP is largely inspired by \fIhtop\fP, though it is not nearly as good or complete.

.SS Options

.TP
.B \-d \fIdelay\fP
Set the poll timeout (or, when operating in log mode, the sleep time) to \fIdelay\fP tenths of a second.
The default delay is 20 (or 2 seconds).

.TP
.B \-l \fIsamples\fP
Enable log mode, print \fIsamples\fP worth of output without color, and then exit.
If \fIsamples\fP is 0 or negative, continue printing indefinitely.

.TP
.B \-H
Display threads separately. This can also be toggled at runtime.

.SS Keyboard Shortcuts
When running, the following keyboard shortcuts are available:

.TP
.B q
Quit \fBtop\fP.

.TP
.B w
Switch to next (right) sort column.

.TP
.B W
Switch to the previous (left) sort column.

.TP
.B T
Toggle the separate display of threads.

.TP
.B h
Show a help message describing these options.

.PP
If \fBtop\fP is redirected to a non-terminal, logging mode will be enabled by default and one sample will be printed.

.SH SEE ALL
.BR libtoaru_procfs (3),
.BR ps (1),
.BR pstree (1),
.BR cpuwidget (1)


.SH AUTHOR
This \fBtop\fP was written by K. Lange <klange@toaruos.org>
