.TH YES 1 "March, 2026"

.SH NAME
\fByes\fP \- repeatedly print a string

.SH SYNOPSIS
\fByes\fP [\fIstring\fP]

.SH DESCRIPTION
Repeatedly prints the string \fBy\fP, or \fIstring\fP, followed by a line feed
to the standard output, suitable for piping to various tools for which the user
does not wish to manually confirm prompts.

.SH OPTIONS
None.

.SH NOTES
Only one argument is accepted. Other arguments will be ignored. This matches
the behavior of other implementations.

