.TH YUTANI-TEST 1 "April, 2026"

.SH NAME
\fByutani\-test\fP \- examine window system events

.SH DESCRIPTION
The \fByutani\-test\fP utility is similar to tools like \fBxev\fP.
It opens a window and receives events from the
.IR compositor (1),
printing a descriptive form of each message it receives and understands.

.SH NOTES
\fByutani\-test\fP only prints messages about mouse and keyboard events,
resize events, focus chanes, and window movement.
.PP
To close \fByutani\-test\fP, press Alt+F4 and send it \fBSIGINT\fP.

.SH SEE ALSO
.BR compositor (1)
