.TH ZCAT 1 "March, 2026"

.SH NAME
\fBzcat\fP \- concatenate compressed files

.SH SYNOPSIS
\fBzcat\fP \fIfile\fP...

.SH DESCRIPTION
This is a wrapper around \fBgunzip \-c\fP. All arguments are passed
to \fBgunzip\fP, so all options supported by that program are also
supported by this one.

.SH SEE ALSO
.BR gunzip (1)
